version: '3'
services:
  laravel-docker-nginx:
    container_name: "laravel-docker-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - laravel-docker-app
    ports:
      - 81:80
    volumes:
      - ./:/src

  laravel-docker-app:
    container_name: "laravel-docker-app"
    build:
      context: ./docker/php
    depends_on:
      - laravel-docker-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  laravel-docker-mysql:
    image: mysql:8.0.33
    command: --max_allowed_packet=32505856
    container_name: "laravel-docker-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel-docker
    ports:
      - 3306:3306

  laravel-docker-redis:
    image: redis:alpine
    container_name: "laravel-docker-redis"
    ports:
      - 16379:6379